#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install ODRIVE Service
      template:
        src: /opt/pgclone/templates/odrive.service
        dest: /etc/systemd/system/odrive.service
        force: yes
      ignore_errors: yes

    - name: Reload ODRIVE Service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: reloaded
        name: odrive

    - name: Create ODRIVE Folders
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - /mnt/odrive
